
import java.awt.*;

/*
 * Program: Assignment 6
 * Input: None
 * Processing: Calculates false and true statements
 * Output: Value, either true or false
 */
/**
 *
 * @author 335561676
 */
public class DrawingArea extends javax.swing.JPanel {

    /**
     * Creates new form DrawingArea
     */
    public DrawingArea() {
        initComponents();
    }
    
    public void paintComponent(Graphics g) {
        g.setColor(Color.MAGENTA);
        g.drawLine(10, 10, 50, 80);
        Font f = new Font("Alba Super", Font.ITALIC+Font.BOLD, 13);
        g.setFont(f);
        g.drawString("Can we do it??", 50, 50);
        for (int i = 5; i <= 150; i += 10) {
            g.setColor(Color.yellow);
            g.drawOval(5, i + 5, 20, 10);
            g.setColor(Color.RED);
            g.drawOval(i, 10, 20, 10);
            g.setColor(Color.BLUE);
            g.drawOval(150, i + 5, 20, 10);
            g.setColor(Color.GREEN);
            g.drawOval(i, 150, 20, 10);
        }
        
        Image img = Toolkit.getDefaultToolkit().getImage("giphy.gif");
        g.drawImage(img, 50, this.getHeight()-img.getHeight(null), this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
